In [ ]:
# import myhda_ur

# from load.loader import Loader
# from visualize.plot import plot_heatmap

In [ ]:
loader = Loader()
scifate = loader.load_as_hda()

In [ ]:
subset = scifate[10:20, 10:20]
subset

HDAData object with:
  n_vars (genes): 10
  n_obs (cells): 10
  X shape: (10, 10)
  layers: ['ntr']
  similarities: []
  trajectories: Yes

Gene-gene similarity

In [ ]:
scifate.compute_similarity(
    data=subset,
    key="ntr",
    kind="gene",
    method="correlation",
    name="gg_ntr"
)

HDAData object with:
  n_vars (genes): 43750
  n_obs (cells): 7404
  X shape: (43750, 7404)
  layers: ['ntr']
  similarities: ['gg_ntr']
  trajectories: Yes

In [ ]:
scifate.similarities["gg_ntr"]

,PRAMEF12,PRAMEF20,AL354712.1,RPL7P11,AL357552.1,RPL23AP19,ENO1-AS1,HMGN2P17,NPPA-AS1,AL021155.1
PRAMEF12,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
PRAMEF20,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
AL354712.1,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
RPL7P11,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0
AL357552.1,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0
RPL23AP19,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0
ENO1-AS1,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0
HMGN2P17,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0
NPPA-AS1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
AL021155.1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0

In [ ]:
gg_ntr = scifate.similarities["gg_ntr"]
plot_heatmap(gg_ntr, "gene")

Cell-cell similarity

In [ ]:
scifate.compute_similarity(
    data=subset,
    key="X",
    kind="cell",
    method="correlation",
    name="cc_X"
)

HDAData object with:
  n_vars (genes): 43750
  n_obs (cells): 7404
  X shape: (43750, 7404)
  layers: ['ntr']
  similarities: ['gg_ntr', 'cc_X']
  trajectories: Yes

In [ ]:
scifate.similarities["cc_X"].head()

,A549.6h.AAAATTAGATTCCG,A549.6h.AAAACTTGCATAAT,A549.8h.AAAAAACTACCGAC,A549.4h.AAAAACTAATTGAG,A549.0h.AAAATTGAATTATA,A549.6h.AAAAGGCTTCTGGA,A549.6h.AAAAACTATCCGCA,A549.2h.AAAAACGTTGAATG,A549.6h.AAAAAGCAAGTAGT,A549.2h.AAAAATCTAGGTTC
A549.6h.AAAATTAGATTCCG,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
A549.6h.AAAACTTGCATAAT,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
A549.8h.AAAAAACTACCGAC,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
A549.4h.AAAAACTAATTGAG,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0
A549.0h.AAAATTGAATTATA,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0

In [ ]:
cc_X = scifate.similarities["cc_X"]
plot_heatmap(cc_X, "cell")

Trajectory-trajectory similarity

In [ ]:
scifate.compute_similarity(
    data=scifate,
    key="ntr",
    kind="trajectory",
    trajectory_id=scifate.trajectories.index[:10],
    method="correlation",
    name="tt_ntr"
)

HDAData object with:
  n_vars (genes): 43750
  n_obs (cells): 7404
  X shape: (43750, 7404)
  layers: ['ntr']
  similarities: ['gg_ntr', 'cc_X', 'tt_ntr']
  trajectories: Yes

In [ ]:
scifate.similarities["tt_ntr"].head()

,traj_1,traj_2,traj_3,traj_4,traj_5,traj_6,traj_7,traj_8,traj_9,traj_10
traj_1,1.000000,0.153213,0.167788,0.158513,0.170313,0.170922,0.175476,0.177563,0.158530,0.166860
traj_2,0.153213,1.000000,0.181102,0.164353,0.195221,0.169728,0.177479,0.179145,0.174914,0.180413
traj_3,0.167788,0.181102,1.000000,0.183113,0.203898,0.196279,0.205856,0.189796,0.188029,0.193451
traj_4,0.158513,0.164353,0.183113,1.000000,0.190287,0.189502,0.190644,0.178852,0.174730,0.186699
traj_5,0.170313,0.195221,0.203898,0.190287,1.000000,0.209611,0.200283,0.213020,0.191868,0.218553

In [ ]:
tt_ntr = scifate.similarities["tt_ntr"]
plot_heatmap(tt_ntr, "trajectories")

<break>

## Biological Use Case Example

#### Use Case: Identify dynamically regulated transcriptional programs during cortisol stress response using highly variable NTR genes

| Analysis | Biological Interpretation |
| --------- | ----------- | 
| Gene-gene similarity | co-regulated dynamic stress-response genes |
| Cell-cell similarity | cells with similar transcriptional stress states |
| Trajectory similarity | similar temporal response paths |

#### 1. Highly Variable Genes (HVGs)

To obtain a meaning subset from the sparse matrix to analyze, first, we need to identify the Highly Variable Genes (HVG). HVGs are genes which are actively changing during stress response. HVGs are identified using NTR values. The NTR variance for each gene across cells is computed to identify genes with the highest variances, which indicate cells that are active, such as initiating stress response.

In [ ]:
top_10_genes = scifate.get_highly_variable_genes(n=10)
print(f'Top 10 gene names: {top_10_genes}')

Top 10 gene names: ['YOD1', 'SGK1', 'PARD6B', 'SMAD7', 'KLF6', 'KLF10', 'CEBPD', 'PLK2', 'ADM', 'GRPEL2']

In [ ]:
# top_10_genes  = ['YOD1', 'SGK1', 'PARD6B', 'SMAD7', 'KLF6', 'KLF10', 'CEBPD', 'PLK2', 'ADM', 'GRPEL2']

In [ ]:
subset_top10 = scifate[top_10_genes, :]
subset_top10

HDAData object with:
  n_vars (genes): 10
  n_obs (cells): 7404
  X shape: (10, 7404)
  layers: ['ntr']
  similarities: []
  trajectories: Yes

In [ ]:
# # top10_subset.layers["ntr"]
# df_test = top10_subset.show(top10_subset.layers["ntr"], n_rows=10, n_cols=5, mode="label")
# df_test

cell_name,A549.4h.AAAAACTCTCTCAA,A549.6h.AAAAAAGAAGTTCA,A549.8h.AAAAACGGAGAATA,A549.4h.AAAACGATCCTGGA,A549.6h.AAAAACTGAATTCC
gene_symbol,,,,,
YOD1,1.0000,1.0000,1.0,1.0000,1.0
SGK1,0.0000,1.0000,0.0,0.0000,1.0
PARD6B,1.0000,1.0000,0.0,0.0000,0.0
SMAD7,0.5451,0.0000,1.0,0.0000,1.0
KLF6,1.0000,1.0000,0.0,1.0000,1.0
KLF10,0.0000,1.0000,1.0,0.0000,1.0
CEBPD,1.0000,1.0000,1.0,0.5575,1.0
PLK2,0.0000,0.0000,0.0,0.0000,1.0
ADM,1.0000,0.5451,0.0,1.0000,0.0
GRPEL2,0.0000,1.0000,0.0,0.0000,0.0

#### 2. Gene-gene similarity

Gene-gene similarity with raw ntr

In [ ]:
scifate.compute_similarity(
    data=subset_top10,
    key="ntr",
    kind="gene",
    method="correlation",
    name="gg_hvg_ntr"
)

HDAData object with:
  n_vars (genes): 43750
  n_obs (cells): 7404
  X shape: (43750, 7404)
  layers: ['ntr']
  similarities: ['gg_hvg_ntr']
  trajectories: Yes

In [ ]:
gg_hvg_ntr = scifate.similarities["gg_hvg_ntr"]
gg_hvg_ntr

,YOD1,SGK1,PARD6B,SMAD7,KLF6,KLF10,CEBPD,PLK2,ADM,GRPEL2
YOD1,1.000000,0.100134,0.062567,0.091714,0.169095,0.065951,0.067229,0.136405,0.122610,0.127108
SGK1,0.100134,1.000000,0.036117,0.083644,0.083344,0.053835,0.125137,0.057928,0.049556,0.077367
PARD6B,0.062567,0.036117,1.000000,0.054674,0.085799,0.064356,0.076837,0.049415,0.087599,0.095415
SMAD7,0.091714,0.083644,0.054674,1.000000,0.110295,0.089687,0.027949,0.090426,0.104398,0.093695
KLF6,0.169095,0.083344,0.085799,0.110295,1.000000,0.114303,0.077222,0.138555,0.169065,0.109297
KLF10,0.065951,0.053835,0.064356,0.089687,0.114303,1.000000,0.029685,0.106823,0.099798,0.073749
CEBPD,0.067229,0.125137,0.076837,0.027949,0.077222,0.029685,1.000000,0.006355,0.020968,0.037757
PLK2,0.136405,0.057928,0.049415,0.090426,0.138555,0.106823,0.006355,1.000000,0.192419,0.094190
ADM,0.122610,0.049556,0.087599,0.104398,0.169065,0.099798,0.020968,0.192419,1.000000,0.098048
GRPEL2,0.127108,0.077367,0.095415,0.093695,0.109297,0.073749,0.037757,0.094190,0.098048,1.000000

In [ ]:
plot_heatmap(sim=gg_hvg_ntr, type="gene", cluster=True)

Gene-gene similarity with trajectory-based mean ntr

In [ ]:
scifate.compute_similarity(
    data=subset_top10,
    key="mean_ntr",
    kind="gene",
    method="correlation",
    name="gg_hvg_mean_ntr"
)

HDAData object with:
  n_vars (genes): 43750
  n_obs (cells): 7404
  X shape: (43750, 7404)
  layers: ['ntr']
  similarities: ['gg_hvg_ntr', 'gg_hvg_mean_ntr']
  trajectories: Yes

In [ ]:
gg_hvg_mean_ntr = scifate.similarities["gg_hvg_mean_ntr"]
gg_hvg_mean_ntr

,YOD1,SGK1,PARD6B,SMAD7,KLF6,KLF10,CEBPD,PLK2,ADM,GRPEL2
YOD1,1.000000,0.776945,0.474773,0.454065,0.556404,0.353280,0.735725,-0.311807,0.546889,-0.533654
SGK1,0.776945,1.000000,0.700703,0.057479,0.799484,-0.122128,0.910030,-0.750463,0.299914,-0.799362
PARD6B,0.474773,0.700703,1.000000,-0.464021,0.744717,-0.636363,0.909213,-0.917815,-0.339614,-0.313180
SMAD7,0.454065,0.057479,-0.464021,1.000000,-0.102760,0.935665,-0.148956,0.575593,0.928657,-0.376392
KLF6,0.556404,0.799484,0.744717,-0.102760,1.000000,-0.350402,0.886445,-0.786754,0.179731,-0.564354
KLF10,0.353280,-0.122128,-0.636363,0.935665,-0.350402,1.000000,-0.347462,0.744392,0.826952,-0.129432
CEBPD,0.735725,0.910030,0.909213,-0.148956,0.886445,-0.347462,1.000000,-0.861710,0.054189,-0.569163
PLK2,-0.311807,-0.750463,-0.917815,0.575593,-0.786754,0.744392,-0.861710,1.000000,0.348633,0.431287
ADM,0.546889,0.299914,-0.339614,0.928657,0.179731,0.826952,0.054189,0.348633,1.000000,-0.557876
GRPEL2,-0.533654,-0.799362,-0.313180,-0.376392,-0.564354,-0.129432,-0.569163,0.431287,-0.557876,1.000000

In [ ]:
plot_heatmap(sim=gg_hvg_mean_ntr, type="gene", cluster=True)

#### 3. Cell-cell similarity

Cell-cell similarity with normalized expression values

In [ ]:
cells_hvg = scifate.get_timepoint_cells(n=2)
cells_hvg

['A549.0h.CGTTACGGCAACCA',
 'A549.0h.ACGCCTCGATGGAG',
 'A549.2h.GAGTCCTACGGCAA',
 'A549.2h.CCTTCCTAAGCGGT',
 'A549.4h.AGTTGTCGAGGTAT',
 'A549.4h.GACGATGAGTTCTC',
 'A549.6h.ATATTCCTTACCAA',
 'A549.6h.GCCTAATCGAACTC',
 'A549.8h.AAGGCGGCAGAGGA',
 'A549.8h.CCGAGACCGTAGCA',
 'A549.10h.GATTATCGTATCAA',
 'A549.10h.GAAAGACCTGGAAT']

In [ ]:
subset_hvg_cell = scifate[top_10_genes, cells_hvg]
subset_hvg_cell

HDAData object with:
  n_vars (genes): 10
  n_obs (cells): 12
  X shape: (10, 12)
  layers: ['ntr']
  similarities: []
  trajectories: Yes

In [ ]:
scifate.compute_similarity(
    data=subset_hvg_cell,
    key="X",
    kind="cell",
    method="correlation",
    name="cc_hvg_X"
)

HDAData object with:
  n_vars (genes): 43750
  n_obs (cells): 7404
  X shape: (43750, 7404)
  layers: ['ntr']
  similarities: ['gg_hvg_ntr', 'gg_hvg_mean_ntr', 'cc_hvg_X']
  trajectories: Yes

In [ ]:
cc_hvg_X = scifate.similarities["cc_hvg_X"]
cc_hvg_X.head()

,A549.0h.CGTTACGGCAACCA,A549.0h.ACGCCTCGATGGAG,A549.2h.GAGTCCTACGGCAA,A549.2h.CCTTCCTAAGCGGT,A549.4h.AGTTGTCGAGGTAT,A549.4h.GACGATGAGTTCTC,A549.6h.ATATTCCTTACCAA,A549.6h.GCCTAATCGAACTC,A549.8h.AAGGCGGCAGAGGA,A549.8h.CCGAGACCGTAGCA,A549.10h.GATTATCGTATCAA,A549.10h.GAAAGACCTGGAAT
A549.0h.CGTTACGGCAACCA,1.000000,0.557330,-0.163137,-0.767532,0.355452,0.023286,-0.419661,0.437261,0.692732,-0.041323,-0.118096,0.580651
A549.0h.ACGCCTCGATGGAG,0.557330,1.000000,0.287607,-0.398935,0.300332,-0.203275,-0.338106,-0.085964,0.501043,0.372256,0.156860,0.633820
A549.2h.GAGTCCTACGGCAA,-0.163137,0.287607,1.000000,0.181268,0.202045,-0.345880,0.265429,-0.227486,-0.454090,0.575101,0.088732,0.159971
A549.2h.CCTTCCTAAGCGGT,-0.767532,-0.398935,0.181268,1.000000,-0.171060,0.218254,0.507829,-0.303359,-0.370632,0.246456,-0.020914,-0.443681
A549.4h.AGTTGTCGAGGTAT,0.355452,0.300332,0.202045,-0.171060,1.000000,0.193531,-0.555189,0.393457,0.415277,-0.162279,-0.062630,0.583338

In [ ]:
plot_heatmap(sim=cc_hvg_X, type="cell", cluster=True)

#### 4. Trajectory-trajectory similarity

Trajectory-trajectory similarity with ntr based on HVGs

In [10]:
top_10_traj = subset_top10.get_highly_dynamic_trajectories(n=10)
top_10_traj

[884, 194, 157, 797, 926, 160, 252, 709, 349, 866]

In [ ]:
scifate.compute_similarity(
    data=scifate,
    key="ntr",
    kind="trajectory",
    trajectory_id=top_10_traj,
    method="correlation",
    name="tt_hvg_ntr"
)

HDAData object with:
  n_vars (genes): 43750
  n_obs (cells): 7404
  X shape: (43750, 7404)
  layers: ['ntr']
  similarities: ['gg_hvg_ntr', 'gg_hvg_mean_ntr', 'cc_hvg_X', 'tt_hvg_ntr']
  trajectories: Yes

In [ ]:
tt_hvg_ntr = scifate.similarities["tt_hvg_ntr"]
tt_hvg_ntr.head()

,traj_884,traj_194,traj_157,traj_797,traj_926,traj_160,traj_252,traj_709,traj_349,traj_866
traj_884,1.000000,0.202188,0.199536,0.214475,0.180266,0.193247,0.193123,0.191457,0.191993,0.201414
traj_194,0.202188,1.000000,0.182796,0.202825,0.178163,0.206497,0.170755,0.188451,0.194947,0.188505
traj_157,0.199536,0.182796,1.000000,0.192822,0.174866,0.173306,0.180421,0.184718,0.174145,0.190824
traj_797,0.214475,0.202825,0.192822,1.000000,0.177453,0.193757,0.180179,0.192785,0.185535,0.199943
traj_926,0.180266,0.178163,0.174866,0.177453,1.000000,0.167112,0.166484,0.164525,0.158190,0.166622

In [ ]:
plot_heatmap(sim=tt_hvg_ntr, type="trajectories", cluster=False)