In [1]:
from load.loader import Loader
from dynamic_models.similarity import compute_similarity
from visualize.plot import plot_heatmap
from dynamic_models.selection import get_highly_variable_genes

In [2]:
loader = Loader()
data = loader.load_as_hda()

In [3]:
subset = data[50:60, 50:60]

In [4]:
subset.show(subset.layers["ntr"], mode="label")

cell_name,A549.0h.CGCGCTCCGGTTCT,A549.2h.CGCGTCCAGCAATA,A549.10h.CGCGGCCTCAATAA,A549.6h.CGCGTTCGCTGCCT,A549.8h.CGCGGTAGATGCGC,A549.6h.CGCGATGCTCGCAA,A549.6h.CGCGTATGGCCGCG,A549.10h.CGCGTCGCAATTAG,A549.4h.CGCGTCGAAGCGCG,A549.6h.CGCGGGAGTAAGCC
gene_symbol,,,,,,,,,,
ACTL8,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
AL357509.1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
LINC01654,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
IGSF21,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
AL031005.1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
AL031728.1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
PPP1R11P1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
AL049569.1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
AL590644.1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
PADI1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

Gene-gene similarity

In [5]:
compute_similarity(
    data=subset,
    key="ntr",
    kind="gene",
    method="correlation",
    target=data,
    name="gene_gene_sim_ntr"
)

HDAData object with:
  n_vars (genes): 43750
  n_obs (cells): 7404
  X shape: (43750, 7404)
  layers: ['ntr']
  similarities: ['gene_gene_sim_ntr']
  trajectories: Yes

In [6]:
data.similarities["gene_gene_sim_ntr"]

,ACTL8,AL357509.1,LINC01654,IGSF21,AL031005.1,AL031728.1,PPP1R11P1,AL049569.1,AL590644.1,PADI1
ACTL8,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
AL357509.1,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
LINC01654,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
IGSF21,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0
AL031005.1,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0
AL031728.1,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0
PPP1R11P1,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0
AL049569.1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0
AL590644.1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
PADI1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0

In [7]:
df1 = data.similarities["gene_gene_sim_ntr"]
plot_heatmap(df1, "gene")

alt.LayerChart(...)

Cell-cell similarity

In [8]:
compute_similarity(
    data=subset,
    key="X",
    kind="cell",
    method="correlation",
    target=data,
    name="cell_cell_X"
)

HDAData object with:
  n_vars (genes): 43750
  n_obs (cells): 7404
  X shape: (43750, 7404)
  layers: ['ntr']
  similarities: ['gene_gene_sim_ntr', 'cell_cell_X']
  trajectories: Yes

In [9]:
data.similarities["cell_cell_X"].head()

,A549.0h.CGCGCTCCGGTTCT,A549.2h.CGCGTCCAGCAATA,A549.10h.CGCGGCCTCAATAA,A549.6h.CGCGTTCGCTGCCT,A549.8h.CGCGGTAGATGCGC,A549.6h.CGCGATGCTCGCAA,A549.6h.CGCGTATGGCCGCG,A549.10h.CGCGTCGCAATTAG,A549.4h.CGCGTCGAAGCGCG,A549.6h.CGCGGGAGTAAGCC
A549.0h.CGCGCTCCGGTTCT,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
A549.2h.CGCGTCCAGCAATA,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
A549.10h.CGCGGCCTCAATAA,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
A549.6h.CGCGTTCGCTGCCT,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0
A549.8h.CGCGGTAGATGCGC,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0

In [10]:
df3 = data.similarities["cell_cell_X"]
plot_heatmap(df3, "cell")

alt.LayerChart(...)

Trajectory-trajectory similarity

In [11]:
compute_similarity(
    data=data,
    key="ntr",
    kind="trajectory",
    trajectory_id=data.trajectories.index[:10],
    method="correlation",
    name="traj_traj_ntr"
)

HDAData object with:
  n_vars (genes): 43750
  n_obs (cells): 7404
  X shape: (43750, 7404)
  layers: ['ntr']
  similarities: ['gene_gene_sim_ntr', 'cell_cell_X', 'traj_traj_ntr']
  trajectories: Yes

In [12]:
data.similarities["traj_traj_ntr"].head()

,traj_1,traj_2,traj_3,traj_4,traj_5,traj_6,traj_7,traj_8,traj_9,traj_10
traj_1,1.000000,0.153213,0.167788,0.158513,0.170313,0.170922,0.175476,0.177563,0.158530,0.166860
traj_2,0.153213,1.000000,0.181102,0.164353,0.195221,0.169728,0.177479,0.179145,0.174914,0.180413
traj_3,0.167788,0.181102,1.000000,0.183113,0.203898,0.196279,0.205856,0.189796,0.188029,0.193451
traj_4,0.158513,0.164353,0.183113,1.000000,0.190287,0.189502,0.190644,0.178852,0.174730,0.186699
traj_5,0.170313,0.195221,0.203898,0.190287,1.000000,0.209611,0.200283,0.213020,0.191868,0.218553

In [13]:
df4 = data.similarities["traj_traj_ntr"]
plot_heatmap(df4, "trajectories")

alt.LayerChart(...)

<break>

## Biological Use Case Example

#### Use Case: Identify dynamically regulated transcriptional programs during cortisol stress response using highly variable NTR genes

| Analysis | Biological Interpretation |
| --------- | ----------- | 
| Gene-gene similarity | Which genes respond together over time? |
| Cell-cell similarity | Which cells show similar stress states? |
| Trajectory similarity | Which temporal responses follow similar dynamics? |

#### 1. Highly Variable Genes (HVGs)

To obtain a meaning subset from the sparse matrix to analyze, first, we need to identify the Highly Variable Genes (HVG). HVGs are genes which are actively changing during stress response. HVGs are identified using NTR values. The NTR variance for each gene across cells is computed to identify genes with the highest variances, which indicate cells that are active, such as initiating stress response.

In [3]:
top_10 = get_highly_variable_genes(data=data, n=10)

In [4]:
print(f'Top 10 gene names: {top_10}')

Top 10 gene names: ['YOD1', 'SGK1', 'PARD6B', 'SMAD7', 'KLF6', 'KLF10', 'CEBPD', 'PLK2', 'ADM', 'GRPEL2']

In [5]:
top10_subset = data[['YOD1', 'SGK1', 'PARD6B', 'SMAD7', 'KLF6', 'KLF10', 'CEBPD', 'PLK2', 'ADM', 'GRPEL2'], :]
top10_subset

HDAData object with:
  n_vars (genes): 10
  n_obs (cells): 7404
  X shape: (10, 7404)
  layers: ['ntr']
  similarities: []
  trajectories: Yes

In [ ]:
# # top10_subset.layers["ntr"]
# df_test = top10_subset.show(top10_subset.layers["ntr"], n_rows=10, n_cols=5, mode="label")
# df_test

cell_name,A549.4h.AAAAACTCTCTCAA,A549.6h.AAAAAAGAAGTTCA,A549.8h.AAAAACGGAGAATA,A549.4h.AAAACGATCCTGGA,A549.6h.AAAAACTGAATTCC
gene_symbol,,,,,
YOD1,1.0000,1.0000,1.0,1.0000,1.0
SGK1,0.0000,1.0000,0.0,0.0000,1.0
PARD6B,1.0000,1.0000,0.0,0.0000,0.0
SMAD7,0.5451,0.0000,1.0,0.0000,1.0
KLF6,1.0000,1.0000,0.0,1.0000,1.0
KLF10,0.0000,1.0000,1.0,0.0000,1.0
CEBPD,1.0000,1.0000,1.0,0.5575,1.0
PLK2,0.0000,0.0000,0.0,0.0000,1.0
ADM,1.0000,0.5451,0.0,1.0000,0.0
GRPEL2,0.0000,1.0000,0.0,0.0000,0.0

Gene-gene similarity with raw ntr

In [8]:
compute_similarity(
    data=top10_subset,
    key="ntr",
    kind="gene",
    method="correlation",
    target=data,
    name="gene_gene_sim_ntr"
)

HDAData object with:
  n_vars (genes): 43750
  n_obs (cells): 7404
  X shape: (43750, 7404)
  layers: ['ntr']
  similarities: ['gene_gene_sim_ntr']
  trajectories: Yes

In [9]:
data.similarities["gene_gene_sim_ntr"]

,YOD1,SGK1,PARD6B,SMAD7,KLF6,KLF10,CEBPD,PLK2,ADM,GRPEL2
YOD1,1.000000,0.100134,0.062567,0.091714,0.169095,0.065951,0.067229,0.136405,0.122610,0.127108
SGK1,0.100134,1.000000,0.036117,0.083644,0.083344,0.053835,0.125137,0.057928,0.049556,0.077367
PARD6B,0.062567,0.036117,1.000000,0.054674,0.085799,0.064356,0.076837,0.049415,0.087599,0.095415
SMAD7,0.091714,0.083644,0.054674,1.000000,0.110295,0.089687,0.027949,0.090426,0.104398,0.093695
KLF6,0.169095,0.083344,0.085799,0.110295,1.000000,0.114303,0.077222,0.138555,0.169065,0.109297
KLF10,0.065951,0.053835,0.064356,0.089687,0.114303,1.000000,0.029685,0.106823,0.099798,0.073749
CEBPD,0.067229,0.125137,0.076837,0.027949,0.077222,0.029685,1.000000,0.006355,0.020968,0.037757
PLK2,0.136405,0.057928,0.049415,0.090426,0.138555,0.106823,0.006355,1.000000,0.192419,0.094190
ADM,0.122610,0.049556,0.087599,0.104398,0.169065,0.099798,0.020968,0.192419,1.000000,0.098048
GRPEL2,0.127108,0.077367,0.095415,0.093695,0.109297,0.073749,0.037757,0.094190,0.098048,1.000000

In [10]:
df1 = data.similarities["gene_gene_sim_ntr"]
plot_heatmap(df1, "gene")

alt.LayerChart(...)

Gene-gene similarity with trajectory-based ntr

In [6]:
compute_similarity(
    data=top10_subset,
    key="mean_ntr",
    kind="gene",
    method="correlation",
    target=data,
    name="gene_gene_sim_mean_ntr"
)

HDAData object with:
  n_vars (genes): 43750
  n_obs (cells): 7404
  X shape: (43750, 7404)
  layers: ['ntr']
  similarities: ['gene_gene_sim_mean_ntr']
  trajectories: Yes

In [7]:
data.similarities["gene_gene_sim_mean_ntr"]

,YOD1,SGK1,PARD6B,SMAD7,KLF6,KLF10,CEBPD,PLK2,ADM,GRPEL2
YOD1,1.000000,0.776945,0.474773,0.454065,0.556404,0.353280,0.735725,0.000000,0.546889,0.000000
SGK1,0.776945,1.000000,0.700703,0.057479,0.799484,0.000000,0.910030,0.000000,0.299914,0.000000
PARD6B,0.474773,0.700703,1.000000,0.000000,0.744717,0.000000,0.909213,0.000000,0.000000,0.000000
SMAD7,0.454065,0.057479,0.000000,1.000000,0.000000,0.935665,0.000000,0.575593,0.928657,0.000000
KLF6,0.556404,0.799484,0.744717,0.000000,1.000000,0.000000,0.886445,0.000000,0.179731,0.000000
KLF10,0.353280,0.000000,0.000000,0.935665,0.000000,1.000000,0.000000,0.744392,0.826952,0.000000
CEBPD,0.735725,0.910030,0.909213,0.000000,0.886445,0.000000,1.000000,0.000000,0.054189,0.000000
PLK2,0.000000,0.000000,0.000000,0.575593,0.000000,0.744392,0.000000,1.000000,0.348633,0.431287
ADM,0.546889,0.299914,0.000000,0.928657,0.179731,0.826952,0.054189,0.348633,1.000000,0.000000
GRPEL2,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.431287,0.000000,1.000000

In [9]:
df2 = data.similarities["gene_gene_sim_mean_ntr"]
plot_heatmap(df2, "gene")

alt.LayerChart(...)