In [1]:
from load.loader import Loader
from dynamic_models.similarity import compute_similarity
from visualize.plot import plot_heatmap

In [2]:
loader = Loader()
data = loader.load_as_hda()

In [3]:
subset = data[50:60, 50:60]

In [4]:
subset.show(subset.layers["ntr"], mode="label")

cell_name,A549.0h.CGCGCTCCGGTTCT,A549.2h.CGCGTCCAGCAATA,A549.10h.CGCGGCCTCAATAA,A549.6h.CGCGTTCGCTGCCT,A549.8h.CGCGGTAGATGCGC,A549.6h.CGCGATGCTCGCAA,A549.6h.CGCGTATGGCCGCG,A549.10h.CGCGTCGCAATTAG,A549.4h.CGCGTCGAAGCGCG,A549.6h.CGCGGGAGTAAGCC
gene_symbol,,,,,,,,,,
ACTL8,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
AL357509.1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
LINC01654,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
IGSF21,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
AL031005.1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
AL031728.1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
PPP1R11P1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
AL049569.1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
AL590644.1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
PADI1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [5]:
compute_similarity(
    data=subset,
    key="ntr",
    kind="gene",
    method="correlation",
    target=data,
    name="gene_gene_sim_ntr"
)

HDAData object with:
  n_vars (genes): 43750
  n_obs (cells): 7404
  X shape: (43750, 7404)
  layers: ['ntr']
  similarities: ['gene_gene_sim_ntr']
  trajectories: Yes

In [6]:
data.similarities["gene_gene_sim_ntr"]

,ACTL8,AL357509.1,LINC01654,IGSF21,AL031005.1,AL031728.1,PPP1R11P1,AL049569.1,AL590644.1,PADI1
ACTL8,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
AL357509.1,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
LINC01654,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
IGSF21,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0
AL031005.1,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0
AL031728.1,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0
PPP1R11P1,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0
AL049569.1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0
AL590644.1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
PADI1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0

In [7]:
df1 = data.similarities["gene_gene_sim_ntr"]
plot_heatmap(df1, "gene")

alt.LayerChart(...)

In [8]:
compute_similarity(
    data=subset,
    key="X",
    kind="cell",
    method="correlation",
    target=data,
    name="cell_cell_X"
)

HDAData object with:
  n_vars (genes): 43750
  n_obs (cells): 7404
  X shape: (43750, 7404)
  layers: ['ntr']
  similarities: ['gene_gene_sim_ntr', 'cell_cell_X']
  trajectories: Yes

In [9]:
data.similarities["cell_cell_X"].head()

,A549.0h.CGCGCTCCGGTTCT,A549.2h.CGCGTCCAGCAATA,A549.10h.CGCGGCCTCAATAA,A549.6h.CGCGTTCGCTGCCT,A549.8h.CGCGGTAGATGCGC,A549.6h.CGCGATGCTCGCAA,A549.6h.CGCGTATGGCCGCG,A549.10h.CGCGTCGCAATTAG,A549.4h.CGCGTCGAAGCGCG,A549.6h.CGCGGGAGTAAGCC
A549.0h.CGCGCTCCGGTTCT,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
A549.2h.CGCGTCCAGCAATA,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
A549.10h.CGCGGCCTCAATAA,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
A549.6h.CGCGTTCGCTGCCT,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0
A549.8h.CGCGGTAGATGCGC,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0

In [10]:
df3 = data.similarities["cell_cell_X"]
plot_heatmap(df3, "cell")

alt.LayerChart(...)

In [12]:
compute_similarity(
    data=data,
    key="ntr",
    kind="trajectory",
    trajectory_id=data.trajectories.index[:10],
    method="correlation",
    name="traj_traj_ntr"
)

HDAData object with:
  n_vars (genes): 43750
  n_obs (cells): 7404
  X shape: (43750, 7404)
  layers: ['ntr']
  similarities: ['gene_gene_sim_ntr', 'cell_cell_X', 'traj_traj_ntr']
  trajectories: Yes

In [13]:
data.similarities["traj_traj_ntr"].head()

,traj_1,traj_2,traj_3,traj_4,traj_5,traj_6,traj_7,traj_8,traj_9,traj_10
traj_1,1.000000,0.153213,0.167788,0.158513,0.170313,0.170922,0.175476,0.177563,0.158530,0.166860
traj_2,0.153213,1.000000,0.181102,0.164353,0.195221,0.169728,0.177479,0.179145,0.174914,0.180413
traj_3,0.167788,0.181102,1.000000,0.183113,0.203898,0.196279,0.205856,0.189796,0.188029,0.193451
traj_4,0.158513,0.164353,0.183113,1.000000,0.190287,0.189502,0.190644,0.178852,0.174730,0.186699
traj_5,0.170313,0.195221,0.203898,0.190287,1.000000,0.209611,0.200283,0.213020,0.191868,0.218553

In [14]:
df4 = data.similarities["traj_traj_ntr"]
plot_heatmap(df4, "trajectories")

alt.LayerChart(...)