In [70]:
from read.loader import Loader
from structure.object import HDAData
from algo.distance import compute_similarity
from visualize.plot import plot_heatmap

In [2]:
loader = Loader()
data = loader.load_as_hda()

In [3]:
subset = data[50:60, 50:60]

In [4]:
subset.show(subset.layers["ntr"], mode="label")

cell_name,A549.0h.CGCGCTCCGGTTCT,A549.2h.CGCGTCCAGCAATA,A549.10h.CGCGGCCTCAATAA,A549.6h.CGCGTTCGCTGCCT,A549.8h.CGCGGTAGATGCGC,A549.6h.CGCGATGCTCGCAA,A549.6h.CGCGTATGGCCGCG,A549.10h.CGCGTCGCAATTAG,A549.4h.CGCGTCGAAGCGCG,A549.6h.CGCGGGAGTAAGCC
gene_symbol,,,,,,,,,,
ACTL8,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
AL357509.1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
LINC01654,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
IGSF21,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
AL031005.1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
AL031728.1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
PPP1R11P1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
AL049569.1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
AL590644.1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
PADI1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [5]:
compute_similarity(
    data=subset,
    key="ntr",
    axis="gene",
    method="correlation",
    target=data,
    name="gene_gene_sim_ntr"
)

HDAData object with:
  n_vars (genes): 43750
  n_obs (cells): 7404
  X shape: (43750, 7404)
  layers: ['ntr']
  similarities: ['gene_gene_sim_ntr']
  trajectories: Yes

In [6]:
data.similarities["gene_gene_sim_ntr"]

,ACTL8,AL357509.1,LINC01654,IGSF21,AL031005.1,AL031728.1,PPP1R11P1,AL049569.1,AL590644.1,PADI1
ACTL8,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
AL357509.1,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
LINC01654,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
IGSF21,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0
AL031005.1,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0
AL031728.1,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0
PPP1R11P1,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0
AL049569.1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0
AL590644.1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
PADI1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0

In [7]:
compute_similarity(
    data=subset,
    key="X",
    axis="cell",
    method="correlation",
    target=data,
    name="cell_cell_X"
)

HDAData object with:
  n_vars (genes): 43750
  n_obs (cells): 7404
  X shape: (43750, 7404)
  layers: ['ntr']
  similarities: ['gene_gene_sim_ntr', 'cell_cell_X']
  trajectories: Yes

In [9]:
data.similarities["cell_cell_X"].head()

,A549.0h.CGCGCTCCGGTTCT,A549.2h.CGCGTCCAGCAATA,A549.10h.CGCGGCCTCAATAA,A549.6h.CGCGTTCGCTGCCT,A549.8h.CGCGGTAGATGCGC,A549.6h.CGCGATGCTCGCAA,A549.6h.CGCGTATGGCCGCG,A549.10h.CGCGTCGCAATTAG,A549.4h.CGCGTCGAAGCGCG,A549.6h.CGCGGGAGTAAGCC
A549.0h.CGCGCTCCGGTTCT,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
A549.2h.CGCGTCCAGCAATA,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
A549.10h.CGCGGCCTCAATAA,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
A549.6h.CGCGTTCGCTGCCT,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0
A549.8h.CGCGGTAGATGCGC,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0

In [ ]:
df1 = data.similarities["gene_gene_sim_ntr"]
plot_heatmap(df1, "gene")

alt.LayerChart(...)

In [69]:
df3 = data.similarities["cell_cell_X"]
plot_heatmap(df3, "cell")

alt.LayerChart(...)